services:
  - type: web
    name: tralalero-contracts
    env: node
    plan: free
    region: oregon # Región más barata
    buildCommand: |
      # Intentar build completo con Rust, usar fallback si falla
      echo "🚀 Iniciando build para Render..."

      # Instalar dependencias Node.js primero (siempre funciona)
      npm install

      # Intentar instalación completa de Rust y soroban-cli
      if (
        apt-get update && 
        apt-get install -y build-essential curl pkg-config libssl-dev git &&
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal &&
        source ~/.cargo/env &&
        rustup target add wasm32-unknown-unknown &&
        export CARGO_NET_RETRY=10 &&
        export CARGO_HTTP_TIMEOUT=300 &&
        export RUSTFLAGS="-C opt-level=2" &&
        (
          cargo install soroban-cli --version 21.5.0 --locked ||
          cargo install soroban-cli --version 20.3.4 --locked ||
          cargo install soroban-cli --version 20.0.0 --locked ||
          cargo install soroban-cli
        ) &&
        soroban --version
      ); then
        echo "✅ Build completo exitoso - Rust y soroban-cli instalados"
      else
        echo "⚠️  Build completo falló, usando fallback..."
        chmod +x ./fallback-build.sh
        ./fallback-build.sh
      fi

      # Crear directorios necesarios
      mkdir -p tralala/dynamic-contracts tralala/compiled

      echo "🎉 Build completado"

    startCommand: npm start

    # Variables de entorno para producción
    envVars:
      - key: NODE_ENV
        value: production
      - key: STELLAR_NETWORK
        value: TESTNET
      - key: STELLAR_HORIZON_URL
        value: https://horizon-testnet.stellar.org
      - key: ENABLE_CONTRACT_COMPILATION
        value: true
      - key: LOG_LEVEL
        value: info
      - key: PORT
        fromService:
          type: web
          name: tralalero-contracts
          property: port

    # Configuración de salud y recursos
    healthCheckPath: /

    # Configuración de build
    buildFilter:
      paths:
        - public/**
        - server.js
        - package.json
        - package-lock.json
        - tralala/contracts/**
        - templates/**
      ignoredPaths:
        - tralala/target/**
        - tralala/dynamic-contracts/**
        - tralala/compiled/**
        - node_modules/**
        - "*.log"
        - ".git/**"
